version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR.UTF-8
      - LC_ALL=ko_KR.UTF-8
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db:3306/mywork
      - SERVER_NAME=localhost:5000
      - SECRET_KEY=my_secret_key
    depends_on:
      - db
    volumes:
      - .:/app
    container_name: quipu_event_app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mywork
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: Asia/Seoul
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: quipu_event_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
